/* Generated By:JJTree: Do not edit this line. ASTAssignIncrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=xenon.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package xenon.parser.ast;

public
class ASTAssignIncrement extends SimpleNode {
  public ASTAssignIncrement(int id) {
    super(id);
  }

  public ASTAssignIncrement(Xenon p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XenonVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ab2016a95d80b8c0d22e0902e6c7a0af (do not edit this line) */
