/* Generated By:JJTree: Do not edit this line. ASTSqrBrackets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=xenon.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package xenon.parser.ast;

public
class ASTSqrBrackets extends SimpleNode {
  public ASTSqrBrackets(int id) {
    super(id);
  }

  public ASTSqrBrackets(Xenon p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XenonVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bff81cc8eb3238bc626ed695e2c9d4e4 (do not edit this line) */
