/* Generated By:JJTree: Do not edit this line. ASTUnaryIncrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=xenon.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package xenon.parser.ast;

public
class ASTUnaryIncrement extends SimpleNode {
  public ASTUnaryIncrement(int id) {
    super(id);
  }

  public ASTUnaryIncrement(Xenon p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XenonVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fafe5a23fc7182d29626dc29988ad1b0 (do not edit this line) */
