/* Generated By:JJTree: Do not edit this line. ASTUnaryMinus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=xenon.interpreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package xenon.parser.ast;

public
class ASTUnaryMinus extends SimpleNode {
  public ASTUnaryMinus(int id) {
    super(id);
  }

  public ASTUnaryMinus(Xenon p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XenonVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ae5ecaf0ac0047220f73da3456b0791 (do not edit this line) */
