/* Generated By:JavaCC: Do not edit this line. XenonTreeConstants.java Version 5.0 */
package xenon.parser.ast;

public interface XenonTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTFNBODY = 4;
  public int JJTFNDEF = 5;
  public int JJTCLASSDEF = 6;
  public int JJTRETURNEXPRESSION = 7;
  public int JJTIFSTATEMENT = 8;
  public int JJTFORLOOP = 9;
  public int JJTFOREACHLOOP = 10;
  public int JJTWHILELOOP = 11;
  public int JJTREFERENCELIST = 12;
  public int JJTARGLIST = 13;
  public int JJTVOID = 14;
  public int JJTASSIGNMENT = 15;
  public int JJTASSIGNINCREMENT = 16;
  public int JJTASSIGNDECREMENT = 17;
  public int JJTOR = 18;
  public int JJTAND = 19;
  public int JJTCOMPEQUAL = 20;
  public int JJTCOMPNEQUAL = 21;
  public int JJTCOMPGTE = 22;
  public int JJTCOMPLTE = 23;
  public int JJTCOMPGT = 24;
  public int JJTCOMPLT = 25;
  public int JJTADD = 26;
  public int JJTSUBTRACT = 27;
  public int JJTTIMES = 28;
  public int JJTDIVIDE = 29;
  public int JJTMODULE = 30;
  public int JJTUNARYNOT = 31;
  public int JJTUNARYPLUS = 32;
  public int JJTUNARYMINUS = 33;
  public int JJTDOTEXPRESSION = 34;
  public int JJTFNINVOKE = 35;
  public int JJTUNARYINCREMENT = 36;
  public int JJTUNARYDECREMENT = 37;
  public int JJTSQRBRACKETS = 38;
  public int JJTIDENTIFIER = 39;
  public int JJTCHARACTER = 40;
  public int JJTINTEGER = 41;
  public int JJTRATIONAL = 42;
  public int JJTTRUE = 43;
  public int JJTFALSE = 44;
  public int JJTTHIS = 45;
  public int JJTGLOBAL = 46;
  public int JJTNULLLITERAL = 47;
  public int JJTNEWOBJECT = 48;
  public int JJTVARIABLE = 49;
  public int JJTLOCALVARDEF = 50;
  public int JJTLAMBDA = 51;
  public int JJTVECTORLITERAL = 52;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "FnBody",
    "FnDef",
    "ClassDef",
    "ReturnExpression",
    "IfStatement",
    "ForLoop",
    "ForEachLoop",
    "WhileLoop",
    "ReferenceList",
    "ArgList",
    "void",
    "Assignment",
    "AssignIncrement",
    "AssignDecrement",
    "Or",
    "And",
    "CompEqual",
    "CompNequal",
    "CompGTE",
    "CompLTE",
    "CompGT",
    "CompLT",
    "Add",
    "Subtract",
    "Times",
    "Divide",
    "Module",
    "UnaryNot",
    "UnaryPlus",
    "UnaryMinus",
    "DotExpression",
    "FnInvoke",
    "UnaryIncrement",
    "UnaryDecrement",
    "SqrBrackets",
    "Identifier",
    "Character",
    "Integer",
    "Rational",
    "True",
    "False",
    "This",
    "Global",
    "NullLiteral",
    "NewObject",
    "Variable",
    "LocalVarDef",
    "Lambda",
    "VectorLiteral",
  };
}
/* JavaCC - OriginalChecksum=b8ed94084574cd16b90feca1c216d246 (do not edit this line) */
