/* Generated By:JJTree&JavaCC: Do not edit this line. XenonConstants.java */
package xenon.parser.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XenonConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int FN = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int CLASS = 20;
  /** RegularExpression Id. */
  int NEW = 21;
  /** RegularExpression Id. */
  int FOREACH = 22;
  /** RegularExpression Id. */
  int IN = 23;
  /** RegularExpression Id. */
  int THIS = 24;
  /** RegularExpression Id. */
  int GLOBAL = 25;
  /** RegularExpression Id. */
  int NULL = 26;
  /** RegularExpression Id. */
  int LAMBDA = 27;
  /** RegularExpression Id. */
  int OF = 28;
  /** RegularExpression Id. */
  int DEF = 29;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 30;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 31;
  /** RegularExpression Id. */
  int HEX_LITERAL = 32;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 33;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 34;
  /** RegularExpression Id. */
  int EXPONENT = 35;
  /** RegularExpression Id. */
  int STRING_LITERAL = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int LPAREN = 40;
  /** RegularExpression Id. */
  int RPAREN = 41;
  /** RegularExpression Id. */
  int LBRACE = 42;
  /** RegularExpression Id. */
  int RBRACE = 43;
  /** RegularExpression Id. */
  int LBRACKET = 44;
  /** RegularExpression Id. */
  int RBRACKET = 45;
  /** RegularExpression Id. */
  int SEMICOLON = 46;
  /** RegularExpression Id. */
  int COMMA = 47;
  /** RegularExpression Id. */
  int DOT = 48;
  /** RegularExpression Id. */
  int PP = 49;
  /** RegularExpression Id. */
  int MM = 50;
  /** RegularExpression Id. */
  int ASSIGN = 51;
  /** RegularExpression Id. */
  int PEQ = 52;
  /** RegularExpression Id. */
  int MEQ = 53;
  /** RegularExpression Id. */
  int UEQ = 54;
  /** RegularExpression Id. */
  int EQ = 55;
  /** RegularExpression Id. */
  int GT = 56;
  /** RegularExpression Id. */
  int LT = 57;
  /** RegularExpression Id. */
  int LE = 58;
  /** RegularExpression Id. */
  int GE = 59;
  /** RegularExpression Id. */
  int NE = 60;
  /** RegularExpression Id. */
  int HOOK = 61;
  /** RegularExpression Id. */
  int COLON = 62;
  /** RegularExpression Id. */
  int PLUS = 63;
  /** RegularExpression Id. */
  int SUBT = 64;
  /** RegularExpression Id. */
  int STAR = 65;
  /** RegularExpression Id. */
  int SLASH = 66;
  /** RegularExpression Id. */
  int REM = 67;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "\"IF\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"FUN\"",
    "\"RETURN\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"WHILE\"",
    "\"CLASS\"",
    "\"NEW\"",
    "\"FOREACH\"",
    "\"IN\"",
    "\"THIS\"",
    "\"GLOBAL\"",
    "\"NULL\"",
    "\"LAMBDA\"",
    "\"OF\"",
    "\"DEF\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"@=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"?\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
