/* Generated By:JavaCC: Do not edit this line. XenonVisitor.java Version 5.0 */
package xenon.parser.ast;

public interface XenonVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCode node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTParmlist node, Object data);
  public Object visit(ASTFnBody node, Object data);
  public Object visit(ASTFnDef node, Object data);
  public Object visit(ASTClassDef node, Object data);
  public Object visit(ASTReturnExpression node, Object data);
  public Object visit(ASTIfStatement node, Object data);
  public Object visit(ASTForLoop node, Object data);
  public Object visit(ASTForEachLoop node, Object data);
  public Object visit(ASTWhileLoop node, Object data);
  public Object visit(ASTReferenceList node, Object data);
  public Object visit(ASTArgList node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTAssignIncrement node, Object data);
  public Object visit(ASTAssignDecrement node, Object data);
  public Object visit(ASTOr node, Object data);
  public Object visit(ASTAnd node, Object data);
  public Object visit(ASTCompEqual node, Object data);
  public Object visit(ASTCompNequal node, Object data);
  public Object visit(ASTCompGTE node, Object data);
  public Object visit(ASTCompLTE node, Object data);
  public Object visit(ASTCompGT node, Object data);
  public Object visit(ASTCompLT node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSubtract node, Object data);
  public Object visit(ASTTimes node, Object data);
  public Object visit(ASTDivide node, Object data);
  public Object visit(ASTModule node, Object data);
  public Object visit(ASTUnaryNot node, Object data);
  public Object visit(ASTUnaryPlus node, Object data);
  public Object visit(ASTUnaryMinus node, Object data);
  public Object visit(ASTDotExpression node, Object data);
  public Object visit(ASTFnInvoke node, Object data);
  public Object visit(ASTUnaryIncrement node, Object data);
  public Object visit(ASTUnaryDecrement node, Object data);
  public Object visit(ASTSqrBrackets node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTCharacter node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTRational node, Object data);
  public Object visit(ASTTrue node, Object data);
  public Object visit(ASTFalse node, Object data);
  public Object visit(ASTThis node, Object data);
  public Object visit(ASTGlobal node, Object data);
  public Object visit(ASTNullLiteral node, Object data);
  public Object visit(ASTNewObject node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTLocalVarDef node, Object data);
  public Object visit(ASTLambda node, Object data);
  public Object visit(ASTVectorLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=7ecb5e35329c108380c8095b51b87a35 (do not edit this line) */
